// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MathGrpc.service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MathGrpc {

  /// <summary>Holder for reflection information generated from MathGrpc.service.proto</summary>
  public static partial class MathGrpcServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for MathGrpc.service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MathGrpcServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZNYXRoR3JwYy5zZXJ2aWNlLnByb3RvGhZNYXRoR3JwYy5tZXNzYWdlLnBy",
            "b3RvMm8KCE1hdGhHcnBjEh8KA0FkZBILLkFkZFJlcXVlc3QaCy5JbnRNZXNz",
            "YWdlEh8KA1N1YhILLlN1YlJlcXVlc3QaCy5JbnRNZXNzYWdlEiEKA1N1bRIL",
            "LlN1bVJlcXVlc3QaCy5JbnRNZXNzYWdlKAFCC6oCCE1hdGhHcnBjYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MathGrpc.MathGrpcMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
