// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MathGrpc.service.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace MathGrpc {
  public static partial class MathGrpc
  {
    static readonly string __ServiceName = "MathGrpc";

    static readonly grpc::Marshaller<global::MathGrpc.AddRequest> __Marshaller_AddRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MathGrpc.AddRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MathGrpc.IntMessage> __Marshaller_IntMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MathGrpc.IntMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MathGrpc.SubRequest> __Marshaller_SubRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MathGrpc.SubRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MathGrpc.SumRequest> __Marshaller_SumRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MathGrpc.SumRequest.Parser.ParseFrom);

    static readonly grpc::Method<global::MathGrpc.AddRequest, global::MathGrpc.IntMessage> __Method_Add = new grpc::Method<global::MathGrpc.AddRequest, global::MathGrpc.IntMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Add",
        __Marshaller_AddRequest,
        __Marshaller_IntMessage);

    static readonly grpc::Method<global::MathGrpc.SubRequest, global::MathGrpc.IntMessage> __Method_Sub = new grpc::Method<global::MathGrpc.SubRequest, global::MathGrpc.IntMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Sub",
        __Marshaller_SubRequest,
        __Marshaller_IntMessage);

    static readonly grpc::Method<global::MathGrpc.SumRequest, global::MathGrpc.IntMessage> __Method_Sum = new grpc::Method<global::MathGrpc.SumRequest, global::MathGrpc.IntMessage>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "Sum",
        __Marshaller_SumRequest,
        __Marshaller_IntMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::MathGrpc.MathGrpcServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MathGrpc</summary>
    public abstract partial class MathGrpcBase
    {
      public virtual global::System.Threading.Tasks.Task<global::MathGrpc.IntMessage> Add(global::MathGrpc.AddRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::MathGrpc.IntMessage> Sub(global::MathGrpc.SubRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::MathGrpc.IntMessage> Sum(grpc::IAsyncStreamReader<global::MathGrpc.SumRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MathGrpc</summary>
    public partial class MathGrpcClient : grpc::ClientBase<MathGrpcClient>
    {
      /// <summary>Creates a new client for MathGrpc</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MathGrpcClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MathGrpc that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MathGrpcClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MathGrpcClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MathGrpcClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::MathGrpc.IntMessage Add(global::MathGrpc.AddRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Add(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MathGrpc.IntMessage Add(global::MathGrpc.AddRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Add, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MathGrpc.IntMessage> AddAsync(global::MathGrpc.AddRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AddAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MathGrpc.IntMessage> AddAsync(global::MathGrpc.AddRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Add, null, options, request);
      }
      public virtual global::MathGrpc.IntMessage Sub(global::MathGrpc.SubRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Sub(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MathGrpc.IntMessage Sub(global::MathGrpc.SubRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Sub, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MathGrpc.IntMessage> SubAsync(global::MathGrpc.SubRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SubAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MathGrpc.IntMessage> SubAsync(global::MathGrpc.SubRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Sub, null, options, request);
      }
      public virtual grpc::AsyncClientStreamingCall<global::MathGrpc.SumRequest, global::MathGrpc.IntMessage> Sum(grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Sum(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::MathGrpc.SumRequest, global::MathGrpc.IntMessage> Sum(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_Sum, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MathGrpcClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MathGrpcClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MathGrpcBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Add, serviceImpl.Add)
          .AddMethod(__Method_Sub, serviceImpl.Sub)
          .AddMethod(__Method_Sum, serviceImpl.Sum).Build();
    }

  }
}
#endregion
