// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MathGrpc.service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MathGrpc {

  /// <summary>Holder for reflection information generated from MathGrpc.service.proto</summary>
  public static partial class MathGrpcServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for MathGrpc.service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MathGrpcServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZNYXRoR3JwYy5zZXJ2aWNlLnByb3RvEgRtYXRoGhZNYXRoR3JwYy5tZXNz",
            "YWdlLnByb3RvMsYBCghNYXRoR3JwYxIpCgNBZGQSEC5tYXRoLkFkZFJlcXVl",
            "c3QaEC5tYXRoLkludE1lc3NhZ2USKQoDU3ViEhAubWF0aC5TdWJSZXF1ZXN0",
            "GhAubWF0aC5JbnRNZXNzYWdlEisKA1N1bRIQLm1hdGguU3VtUmVxdWVzdBoQ",
            "Lm1hdGguSW50TWVzc2FnZSgBEjcKD1N1bVNlcnZlclN0cmVhbRIQLm1hdGgu",
            "U3VtUmVxdWVzdBoQLm1hdGguSW50TWVzc2FnZTABQguqAghNYXRoR3JwY2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MathGrpc.MathGrpcMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
