// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MathGrpc.service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MathGrpc {

  /// <summary>Holder for reflection information generated from MathGrpc.service.proto</summary>
  public static partial class MathGrpcServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for MathGrpc.service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MathGrpcServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZNYXRoR3JwYy5zZXJ2aWNlLnByb3RvGhZNYXRoR3JwYy5tZXNzYWdlLnBy",
            "b3RvMp4BCghNYXRoR3JwYxIfCgNBZGQSCy5BZGRSZXF1ZXN0GgsuSW50TWVz",
            "c2FnZRIfCgNTdWISCy5TdWJSZXF1ZXN0GgsuSW50TWVzc2FnZRIhCgNTdW0S",
            "Cy5TdW1SZXF1ZXN0GgsuSW50TWVzc2FnZSgBEi0KD1N1bVNlcnZlclN0cmVh",
            "bRILLlN1bVJlcXVlc3QaCy5JbnRNZXNzYWdlMAFCC6oCCE1hdGhHcnBjYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MathGrpc.MathGrpcMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
